version: '3.8'

volumes:
  datafiles: null
services:
  mysql:
    image: mysql:8.0.0
    container_name: mysql_basket
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_TCP_PORT=3306
    command: --init-file /home/db.sql
    volumes:
      - datafiles:/var/lib/mysql
      - ./config/db.sql:/home/db.sql
    restart: always
    networks:
      - rete
  php:
    image: yiisoftware/yii2-php:7.3-apache
    container_name: yii_web_basket
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=secret
      - MYSQL_DBNAME=basket
    ports:
      - 8000:80
    depends_on:
      - mysql
    networks:
      - rete
networks:
  rete:
    driver: bridge